User.create!(nickname: 'テスト太郎', email: 'test@test.com', password: '123456', first_name: 'テスト', last_name: '太朗')
User.create!(nickname: 'テスト次郎', email: 'te@st.com', password: '456789', first_name: 'テスト', last_name: '次郎')
Expense.create!(expense_item_id: 1, price: 62500, memo: '家賃代', user_id: 1)
Expense.create!(expense_item_id: 2, price: 10000, memo: '水道代', user_id: 1)
Expense.create!(expense_item_id: 3, price: 5000, memo: '携帯代', user_id: 1)
Expense.create!(expense_item_id: 5, price: 500, memo: 'お菓子', user_id: 1)
Expense.create!(expense_item_id: 5, price: 500, memo: 'お菓子', user_id: 1)
Expense.create!(expense_item_id: 6, price: 300, memo: 'ペーパー', user_id: 1)
Expense.create!(expense_item_id: 7, price: 12500, memo: 'ユニクロ', user_id: 1)
Expense.create!(expense_item_id: 8, price: 5000, memo: '美容院', user_id: 1)
Expense.create!(expense_item_id: 9, price: 20000, memo: '交際費', user_id: 1)
Expense.create!(expense_item_id: 9, price: 18000, memo: '公債費', user_id: 1)
Expense.create!(expense_item_id: 10, price: 3000, memo: '病院代', user_id: 1)
Expense.create!(expense_item_id: 11, price: 10000, memo: '出産祝い', user_id: 1)
Income.create!(income_item_id: 1, price: 300000, memo: '給料', user_id: 1)
Income.create!(income_item_id: 1, price: 300000, memo: '給料', user_id: 1)
Income.create!(income_item_id: 2, price: 10000, memo: '残業！', user_id: 1)
Income.create!(income_item_id: 2, price: 10000, memo: '残業！', user_id: 1)
Income.create!(income_item_id: 2, price: 10000, memo: '残業！', user_id: 1)
Income.create!(income_item_id: 3, price: 10000, memo: 'ボーナス', user_id: 1)
Income.create!(income_item_id: 3, price: 8000, memo: 'ボーナス', user_id: 1)
Income.create!(income_item_id: 8, price: 20000, memo: '副業', user_id: 1)
Income.create!(income_item_id: 11, price: 5000, memo: '還付金', user_id: 1)
Income.create!(income_item_id: 12, price: 3000, memo: 'フリマ', user_id: 1)
Income.create!(income_item_id: 13, price: 10000, memo: '利息', user_id: 1)


